language: python

python:
  - 3.5

script:
  - make style

notifications:
  webhooks:
    urls:
      - http://kivy.org:5000/travisevent
    on_success: always
    on_failure: always
    on_start: always
